spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/logadvisor
spring.datasource.username=admin
spring.datasource.password=secret
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
serpapi.key=7ed81fed9a2c41d455761726ad9ee76020b07387b985a7530ec65c01af887606