spring.application.name=backend

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/logadvisor
spring.datasource.username=admin
spring.datasource.password=secret
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# SerpApi
serpapi.key=dae1d2489200c2fb6aabc1c136671a794bf404fbb0899752106d9efcda490701

# Groq
groq.api-key=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
groq.model=llama-3.3-70b-versatile

# Chroma
chroma.url=http://localhost:8001
chroma.collection=logadvisor_articles

# RAG
rag.min-score=0.7